kind: Job
apiVersion: batch/v1
metadata:
  name: train
spec:
  template:
    spec:
      nodeSelector:
        springfield.uit.no/gpu-type: rtx-3090
      hostIPC: true
      containers:
      - name: train
        image: "hzavadil98/cuda_conda:latest"
        resources:
          requests:
          cpu: "16"
          memory: "20Gi"
          nvidia.com/gpu: 1
        limits:
          cpu: "16"
          memory: "20Gi"
          nvidia.com/gpu: 1
        workingDir: /storage/UiT_FYS-8603/
        command: ["python", "train_f.py"]
        #command: ["python", "train_1vf.py"]
        #command: ["python", "train_4vf.py"]
        #command: ["python", "train_4v2b.py"]
        #command: ["pwd"]
        volumeMounts:
        - name: storage
          mountPath: /storage
        env: 
        - name: WANDB_API_KEY
          valueFrom: 
            secretKeyRef: 
              name: wandb
              key: apikey
      volumes:
      - name: storage
        persistentVolumeClaim:
          claimName: storage
      restartPolicy: OnFailure
  backoffLimit: 0
#gtx-1080-ti, rtx-2080-ti, rtx-3090, or rtx-A6000