kind: Job
apiVersion: batch/v1
metadata:
  name: train1
spec:
  template:
    spec:
      nodeSelector:
        springfield.uit.no/gpu-type: rtx-2080-ti
      hostIPC: true
      containers:
      - name: train
        image: "hzavadil98/fys-8603:latest"
        resources:
          requests:
            nvidia.com/gpu: 1
          limits:
            nvidia.com/gpu: 1
        workingDir: /storage/UiT_FYS-8603/
        command: ["sh", "job_script.sh"]
        #command: ["pwd"]
        volumeMounts:
        - name: storage
          mountPath: /storage
        env: 
        - name: WANDB_API_KEY
          valueFrom: 
            secretKeyRef: 
              name: wandb
              key: apikey
      volumes:
      - name: storage
        persistentVolumeClaim:
          claimName: storage
      restartPolicy: Never
  backoffLimit: 0
#gtx-1080-ti, rtx-2080-ti, rtx-3090, or rtx-A6000